services:
  - type: web
    name: rn-backend-api
    env: node
    region: singapore    # Neon ka region ap-southeast-1 hai, to yeh sahi close region hai
    plan: free

    buildCommand: "npm install"
    startCommand: "node server.js"

    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

      - key: DATABASE_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_ORIGIN
        sync: false

      - key: AGORA_APP_ID
        sync: false
      - key: AGORA_APP_CERTIFICATE
        sync: false
      - key: AGORA_TOKEN_SERVER_URL
        sync: false

      - key: ADMOB_APP_ID
        sync: false
      - key: ADMOB_AD_UNIT_ID
        sync: false

      - key: HEALTHCHECK_SECRET
        sync: false